### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ko-Hi-Dev** [unix3dgforce/lpunpack#2]
So I've been trying to unpack
OnePlus Nord 2 super images

But when extracting some partitions i get

python3 lpunpack.py -p odm super.img p
Traceback (most recent call last):
  File "/storage/emulated/0/Download/update/lpunpack.py", line 450, in <module>
    LpUnpack(**vars(namespace)).unpack()
  File "/storage/emulated/0/Download/update/lpunpack.py", line 405, in unpack
    self.Extract(partition, metadata)
  File "/storage/emulated/0/Download/update/lpunpack.py", line 369, in Extract
    extent = metadata.extents[partition.first_extent_index]
IndexError: list index out of range

This happens both on PC and phone, 

Just to add, if i don't specify any partition all files well be [OK] but they will be broken

**Comment by unix3dgforce** [comment]
Hi,
could you provide a link to download the firmware so i can check the errors

**Comment by unix3dgforce** [comment]
I fixed extract broken images
